name: GitHub Auto Publish
description: >
  Automate publish a GitHub release if find an unpublished version in
  `CHANGELOG.md` (`Keep a Changelog` format).
author: Alireza Hosseini
branding:
  icon: upload-cloud
  color: green

inputs:
  github-token:
    description: GitHub token.
    required: true

  files:
    description: Files to be uploaded as release assets.
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Install dependencies
      run: >
        python3 -m pip install
        -r ${{ github.action_path }}/requirements/main.txt
      shell: bash

    - name: Get publish info
      id: publish-info
      run: >
        python3 ${{ github.action_path }}/scripts/publish_info.py
        ${{ inputs.github-token }}
        ${{ github.repository }}
      shell: bash

    - run: echo version=${{ steps.publish-info.outputs.version }}
      shell: bash

    - name: Get release info
      id: release-info
      run: >
        python3 ${{ github.action_path }}/scripts/release_info.py
        ${{ steps.publish-info.outputs.version }}
      shell: bash

    - run: |
        echo release-notes=$RELEASE_NOTES
      shell: bash
      env:
        RELEASE_NOTES: ${{ steps.release-info.outputs.release-notes }}

    - name: Publish GitHub release
      run: >
        gh release create
        ${{ steps.publish-info.outputs.version }}
        ${{ inputs.files }}
        --title "${{ steps.publish-info.outputs.version }}"
        --notes "${{ steps.release-info.outputs.release-notes }}"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
